version: '3'
services:
  web:
    build: .
    ports:
    - "3000:80"
    environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=secret
    - DB_HOST=db
    - REDIS_HOST=redis
    links:
    - redis
    - db
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=secret
    - POSTGRES_DB=paystackdb

